name = "PlotGraphviz"
uuid = "78a92bc3-407c-4e2f-aae5-75bb47a6fe36"
authors = ["tragisch <uwe@roettgermann.de> and contributors"]
version = "0.6.3"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Graphviz_jll = "3c863552-8265-54e4-a6dc-903eb78fde85"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"

[compat]
DataStructures = "0.18"
Graphs = "1"
Graphviz_jll = "2"
ParserCombinator = "2"
SimpleWeightedGraphs = "1"
StructEquality = "2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
